Item.create(name: "10X Sugar")
Item.create(name: "Alcohol Cleaning")
Item.create(name: "Almond Milk Shelf Stable")
Item.create(name: "Aloe")
Item.create(name: "AP Flour Small")
Item.create(name: "Applesauce")
Item.create(name: "Bacon")
Item.create(name: "Bagels")
Item.create(name: "Bleach")
Item.create(name: "Body Wipes")
Item.create(name: "Bread")
Item.create(name: "Bread Flour")
Item.create(name: "Brown Sugar")
Item.create(name: "Buns")
Item.create(name: "Canned Beans")
Item.create(name: "Canola Oil")
Item.create(name: "Canola Spray")
Item.create(name: "Cash Dale")
Item.create(name: "Cash Sandy")
Item.create(name: "CBD Oil")
Item.create(name: "Cereal")
Item.create(name: "Chicken")
Item.create(name: "Chicken Broth/No Chick")
Item.create(name: "Clorox Wipes")
Item.create(name: "Cornmeal")
Item.create(name: "Creamer Sandy")
Item.create(name: "Disposable Masks")
Item.create(name: "Filters Brita")
Item.create(name: "Filters Distiller")
Item.create(name: "Flea Spray")
Item.create(name: "Frozen Meals")
Item.create(name: "Fruit Canned")
Item.create(name: "Fruit Frozen")
Item.create(name: "Hamburger Lily")
Item.create(name: "Hydrogen Peroxide")
Item.create(name: "Ice Bagged")
Item.create(name: "Instant Meals")
Item.create(name: "Jam")
Item.create(name: "Juices Can or Bottle")
Item.create(name: "Juices Frozen")
Item.create(name: "Kleenex")
Item.create(name: "Meat Dale")
Item.create(name: "Muffins")
Item.create(name: "Paper Bowls")
Item.create(name: "Paper Cups")
Item.create(name: "Paper Plates")
Item.create(name: "Paper Towels")
Item.create(name: "Pasta")
Item.create(name: "Personal Wipes")
Item.create(name: "Plastic Gloves")
Item.create(name: "Pork Dale")
Item.create(name: "Rice Lily")
Item.create(name: "Soap Bars")
Item.create(name: "Soap Liquid")
Item.create(name: "Soup Sandy")
Item.create(name: "Sun Lotion Dale")
Item.create(name: "Sun Lotion Sandy")
Item.create(name: "TP")
Item.create(name: "Veggie Broth")
Item.create(name: "Veggies Canned")
Item.create(name: "Veggies Frozen")
Item.create(name: "Washable Masks")
Item.create(name: "Water Electrolyte")
Item.create(name: "Water Gallons")
Item.create(name: "Windex")

Location.create(name: "Inside Storage")
Location.create(name: "Indoor Freezer")
Location.create(name: "EMER USE")
Location.create(name: "Camper")